version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ferdn4ndo"
    assignees:
      - "ferdn4ndo"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      vue:
        patterns:
          - "@vue/*"
          - "vue*"
          - "vite*"
      icons:
        patterns:
          - "@fortawesome/*"
      lint:
        patterns:
          - "eslint*"
          - "stylelint*"
          - "prettier*"
          - "@rushstack/eslint*"
      typescript:
        patterns:
          - "@tsconfig/*"
          - "@types/*"
          - "typescript*"
      sass:
        patterns:
          - "postcss-html*"
          - "sass*"
      boilerplate:
        patterns:
          - "pinia*"
          - "cypress*"
          - "jsdom*"
          - "npm-run-all2*"
          - "start-server-and-test*"

  # Fetch and update latest `github-actions` packages
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ferdn4ndo"
    assignees:
      - "ferdn4ndo"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
